@baseUrl = http://localhost:5281
##################################################


################################################## SwapPlayer
POST {{baseUrl}}/SwapPlayer/OnPostSwapPlayers
#####
